image: ubuntu:latest
stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: Staging
    url: "$SERVER_URL"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no root@"$SERVER_URL" 'sh /home/apps/enwie-backend/run.sh deploy'
  when: manual
  only:
    - master